# -*- coding: utf-8 -*-
"""LVADSUSR201_Yuvan Barathi C.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1js-ChKcr5rr5FVBsohNFNPm32tmmDGao

LAB - 1
"""

#1

prop = input('Enter the commercial property type: ')
len = int(input('Length in meters: '))
wid = int(input('Width in meters: '))
area = len*wid
if area < 5000:
  print('Your',prop, 'has a small area of',area, 'm2')
elif area < 10000:
  print('Your',prop, 'has a medium area of',area, 'm2')
else:
  print('Your',prop, 'has a large area of',area, 'm2')

#2

def bmi(w,h):
  val = (w/h**2)
  if val < 18.5:
    print('Your BMI is:', val, '. Focus on improving your body weight. Include proteins and fats in ur diet.')
  elif val <25:
    print('Your BMI is:', val, '. Keep following your diet to stay in this fit range of BMI.')
  else:
    print('Your BMI is:', val, '. Start jogging everyday and spend time on fat burning workouts. Include vegetable in ur diet.')
h = float(input('Height in meters: '))
w = float(input('Weight in kgs: '))
bmi(w,h)

#3

def add_student(sd, s_name, sub, grade):
  if s_name not in sd:
    sd[s_name] = {}
  if sub not in sd:
    sd[s_name][sub] = grade
def update_student(sd, s_name, sub, grade):
  if sub in sd[s_name]:
    sd[s_name][sub] = grade
def retrieve_student(sd, s_name):
  if s_name in sd:
    return sd[s_name]
  else:
    return 0

students = {}
while True:
  print("\nEducational Record System")
  print("1. Add Students")
  print("2. Update Students")
  print("3. Retrieve Students")
  print("4. Print the records")
  print("5. Exit")
  choice = int(input("Enter your choice (1/2/3/4/5): "))
  if choice == 1:
    name = input('Enter student name: ')
    subject = input('Enter subject: ')
    grade = int(input('Enter grade: '))
    add_student(students, name, subject, grade)
    print('Student record added.')
  elif choice == 2:
    name = input('Enter student name: ')
    subject = input('Enter subject: ')
    grade = int(input('Enter grade: '))
    update_student(students, name, subject, grade)
    print('Student record updated.')
  elif choice == 3:
    name = input('Enter student name: ')
    grade = retrieve_student(students, name)
    print(f"Student {name} : {grade}")
  elif choice == 4:
    for i in students:
      print(i)
  elif choice == 5:
    print('Exiting program')
    break
  else:
    print('Enter a valid choice!')

"""LAB -2"""

#4

age = int(input("Enter your age: "))
if age < 13:
  print('User is recommended children content')
if age < 18:
  print('User is recommended teen content')
if age < 40:
  print('User is recommended adult content')
else:
  print('User is recommended senior citizen content')

#5

sub_ids = [1,2,3,4,5,6,7,8,9,10]
ans = []
for i in sub_ids:
  if i%2 == 0:
    ans.append(i)
print("Subcribers with even ID: ", ans)

#6

pwd = 'IA1@thehive'
while True:
  user_input = input('Enter the password: ')
  if user_input == pwd:
    print('Access granted')
    break
  else:
    print('Incorrect password')

"""LAB - 3"""

#7

import statistics

def feedback_analysis(s):
  ans = statistics.fmean(s)
  return ans

n = int(input('Enter the number of feedbacks: '))
scores=[]
for i in range(n):
  x = float(input(f"Enter the score of customer {i+1} :"))
  scores.append(x)

res = feedback_analysis(scores)

if res < 5:
  print(res, ' is a below average feedback score')
elif res < 8:
  print(res, ' is an average feedback score')
else:
  print(res, ' is a good feedback scores')

#8

def vowel(s):
  c = 0
  for i in s:
    if i.lower() == 'a' or i.lower() == 'e' or i.lower() == 'i' or i.lower() == 'o' or i.lower() == 'u':
      c+=1
  return c

string = 'Apple'
ans = vowel(string)
print('No. of vowels: ',ans)

#9

"""LAB - 4"""

#10

try:
  savings = float(input('Enter your savings amount: '))
  loan_amt = float(input('Enter your loan amount: '))
  loan_yrs = int(input('Enter the no. of years: '))
  r = 12
  amount = loan_amt*((1+r/100)**loan_yrs)
  interest = amount-loan_amt
  print("Your loan interest: ", interest)
except:
  print('Unknown error occured!')

#11

try:
  name = input('Enter your name: ')
  age = int(input('Enter your age: '))
  choice = int(input('Enter your poll choice: '))
  print('Your vote has been registered!')
except ValueError:
  print('Incorrect value format')

#12

try:
  a = 5
  b = 0
  print('Sum: ', a+b)
  print('Difference: ', a-b)
  print('Product: ', a*b)
  print('Division: ', a/b)
except ZeroDivisionError:
  print('Cant divide a number by zero!')

"""LAB - 5"""

#13

log_file = '22-04-2024, Server uptime for the day: 12 hours.'
file = open('/content/test.txt', 'a')
file.write('')
file = open('/content/test.txt', 'a')
file.write(log_file)

#14

file = open('/content/test.txt', 'r')
file.read()

#15

file = open('/content/test.txt', 'a')
file.write("Company's shares have gone up for the day.")
file.write("Stock prices have been the same.")
file.write("Many new recruits have been selected in the industry.")
file = open('/content/test.txt', 'r')
file.read()